config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#home'
  resources :welcome, only: [:index]
  resources :users, only: [:index] do
    member do
      get 'follower', 'following', 'show'
    end
  end

  resources :microposts, only: %i[create destroy] do
    member do
      get 'thumbup'
    end
  end
  resources :relationships, only: %i[create destroy]
  resources :comments, only: %i[index create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  default_scope -> { order(created_at: :desc) }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one :source, class_name: 'Micropost', primary_key: 'source_id', foreign_key: 'id'
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # belongs_to :follower, class_name: "User"
  # belongs_to :following, class_name: "User",foreign_key:"followed_id"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable # , :recoverable,
  attr_accessor :remember_token

  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :followers, class_name: 'User', join_table: 'relationships',
                                      foreign_key: 'followed_id', association_foreign_key: 'follower_id'
  has_and_belongs_to_many :followings, class_name: 'User', join_table: 'relationships',
                                       foreign_key: 'follower_id', association_foreign_key: 'followed_id'

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :email, presence: true, format: { with: /.+@.+/ },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_nil: { on: :update }
  # has_secure_password

  def self.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def login_user
    return if user_signed_in?
    session[:forwarding_url] = request.original_url if request.get?
    flash[:danger] = 'Please Login First'
    redirect_to new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @micropost = Micropost.includes(:comments).find(params[:micropost_id])
    @comments = @micropost.comments.paginate(page: params[:page], per_page: 5)
    @comment = @micropost.comments.build
    render 'index', layout: false
  end

  def create
    @comment = Comment.create(comment_params)
    render 'comments/postcomment', layout: false if @comment.save
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :micropost_id)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :login_user, only: %i[create destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = 'Micropost created!'
      redirect_to current_user
    else
      @user = current_user
      @microposts = @user.microposts.paginate(page: params[:page], per_page: 10)
      render 'users/show'
    end
  end

  def destroy
    @micropost = current_user.microposts.find(params[:id])
    @micropost.destroy
    redirect_to current_user
  end

  def thumbup
    @micropost = Micropost.find(params[:id])
    num = @micropost.thumbup + 1
    @micropost.update_columns(thumbup: num)
    render nothing: true
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :picture, :source_id)
  end

  def picture_size
    return unless picture.size > 5.megabytes
    errors.add(:picture, 'should be less than 5MB')
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :login_user, only: %i[create destroy]
  def create
    @relationship = Relationship.new(
      follower_id: current_user.id,
      followed_id: params[:id]
    )
    redirect_to user_path(id: params[:id]) if @relationship.save
  end

  def destroy
    @relationship = Relationship.find_by(
      followed_id: params[:id],
      follower_id: current_user.id
    )
    @relationship.destroy
    redirect_to user_path(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: %i[edit update]
  before_action :admin_user, only: [:destroy]
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 10)
    @micropost = @user.microposts.build
    # debugger
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def follower
    @users = User.find(params[:id]).followers.paginate(page: params[:page])
    render 'index'
  end

  def following
    @users = User.find(params[:id]).followings.paginate(page: params[:page])
    render 'index'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find_by(id: params[:id])
    redirect_to user_path(@user) unless current_user == @user
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end

  def home
    @user = current_user
    if @user.nil?
      redirect_to welcome_index_path
      return
    end
    ids = @user.followings.pluck(:id)
    ids << current_user.id
    @micropost = @user.microposts.build
    @microposts = Micropost.where(user_id: ids).paginate(page: params[:page], per_page: 5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <span class="user">
    <%= gravatar_for comment.user,size:20 %>
    <%= link_to comment.user.name,comment.user %>
  </span>
  <span class="content">
    <%= comment.content%>
  </span>
</div>

app/views/comments/_post.html.erb
<%= form_for(@comment,class:"form-control",html:{multipart:true}) do |f| %>
  <%= f.text_field :user_id,value:current_user.id,type:"hidden" %>
  <%= f.text_field :micropost_id,value:micropost.id,type:"hidden" %>
  <%= f.text_area :content,class:"comment-content" %>
<% end %>
<%= content_tag(:a,'Comment',class:"btn btn-primary col-xs-2")%>

app/views/comments/_zhuanfa.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Forward</h4>
      </div>
      <%= form_for :micropost ,url: microposts_path do |f| %>
        <%= f.text_area :content %>
        <%= f.text_field :source_id,value:"",type:"hidden" %>
      <% end %>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Forward</button>
      </div>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<div class="comments">
  <%= render 'post',micropost:@micropost%>
  <p>Comments:</p>
  <% @comments.each do |comment| %>
    <%= render 'comment',comment:comment,micropost:@micropost %>
  <% end %>
  <%= will_paginate @comments,previous_label:"<",next_label:">" %>
</div>

app/views/comments/postcomment.html.erb
<div class="comment">
  <span class="user">
    <%= gravatar_for @comment.user,size:20 %>
    <%= link_to @comment.user.name,@comment.user %>
  </span>
  <span class="content">
    <%= @comment.content%>
  </span>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer bottom">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete%>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
        <li><%= link_to "Help", 'http://guides.ruby-china.org/' %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application.css', media: 'all'%>
    <%= javascript_include_tag 'application.js' %>
    <script src="http://cdn.static.runoob.com/libs/angular.js/1.4.6/angular.min.js"></script>

  </head>

  <body>
    <%= render 'layouts/header'%>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development? %> 
  </body>
</html>

app/views/microposts/_micropost.html.erb
<div class="micropost">
  <%= content_tag :span,class:"user" do %>
    <%= gravatar_for micropost.user,size:20 %>
    <%= link_to micropost.user.name,micropost.user %>
  <% end %>

  <%= content_tag(:span,micropost.content,class:"content") %>
  <% unless micropost.source_id.nil? %>
    <%= content_tag(:span,class:"content") do %>
      <%= render 'microposts/micropost',micropost: micropost.source%> <!--#FIXME -->
    <% end %>
  <% end %>

  <%= image_tag micropost.picture.url,height: '120', width: '180' if micropost.picture? %>
  <p class="micropost-footer">
      <%= link_to '','#myModal',class:"glyphicon glyphicon-share-alt" ,data:{toggle:"modal",id:micropost.id}%>

      <%= link_to "(#{micropost.comments.count})",'#',class:"glyphicon glyphicon-option-horizontal" ,data:{id:micropost.id}%>

      <%= link_to "(#{micropost.thumbup})",'#',class:"glyphicon glyphicon-thumbs-up" ,data:{id:micropost.id} %>

      <% if user_signed_in? && micropost.user.id == current_user.id %>
        <%= link_to '',micropost_path(micropost),class:"glyphicon glyphicon-trash",method: :delete,data:{confirm:'Sure?'} %>
      <% end %>
  </p>
</div>

app/views/microposts/_post.html.erb
<%= form_for(micropost,class:"form-control",html:{multipart:true}) do |f| %>
  <%= render 'shared/error_messages' ,record:micropost %>
  <%= f.text_area :content,class:"micropost-content" %>
  <%= f.submit 'Post',class:"btn btn-primary col-xs-2" %>
  <span class="picture">
    <%= f.file_field :picture ,accept: 'image/jpeg,image/gif,image/png'%>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_error_messages.html.erb
<% if record.errors.any? %>
  <div id="error_explanation" class="bg-danger">
    <div>
      The form contains <%= pluralize(record.errors.count, "error") %>.
    </div>
    <ul>
      <% record.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_aside.html.erb
<aside class="col-md-4">
  <section class="user_info">
    <%= gravatar_for user,size:80 %>
    <h2><%= link_to user.name,user_path(user) %></h2>

    <ul class="nav nav-pills" role="tablist">
      <li role="presentation">
        <%= link_to "/users/#{user.id}/following" do %>
          <%= 'Following' %>
          <%= content_tag :span,user.followings.count,class: "badge" %>
        <% end %>
      </li>
      <li role="presentation">
        <%= link_to "/users/#{user.id}/follower" do %>
          <%= 'Follower' %>
          <%= content_tag :span,user.followers.count,class: "badge" %>
        <% end %>
      </li>
      
      <% if user.id != current_user.id %>
        <% if current_user.followings.include?(user) %>
          <li role="presentation"><%= button_to 'unFollow',relationship_path, class: "btn btn-warning",params:{id:user.id},method: :delete %></li>
        <% else %>
          <li role="presentation"><%= button_to 'Follow',relationships_path, class: "btn btn-info",params:{id:user.id},method: :post %></li>
        <% end %>
      <% end %>
    </ul>
  </section>
  <% if user_signed_in? && current_user.id == user.id %>
    <%= render 'microposts/post',micropost:micropost %>
  <% end %>
</aside>

app/views/users/index.html.erb
<h1>Users</h1>
<%= will_paginate @users,previous_label:"Previous",next_label:"Next"%>
<ul class="users">
  <% @users.each do |user| %>
  <li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? %>
      | <%= link_to 'delete',user_path(user),method: :delete %>
    <% end %>
  </li>
  <% end %>
</ul>

<%= will_paginate @users,previous_label:"Previous",next_label:"Next"%>

app/views/users/show.html.erb
<div class="row">
  <%=render 'users/aside',user:@user,micropost:@micropost %>
  <div class="col-md-6">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <%= render @microposts %>
      <%= will_paginate @microposts,previous_label:"Previous",next_label:"Next",inner_window:1,outer_window:1 %>
    <% end %>
  </div>
  <%= render 'comments/zhuanfa'%>
</div>

app/views/welcome/_footer.html.erb
<footer class="footer">
	<small>
		The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", '#' %></li>
			<li><%= link_to "Contact", '#' %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/welcome/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "sample app", '#', id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", '#' %></li>
				<li><%= link_to "Help", '#' %></li>
				<li><%= link_to "Log in", '#' %></li>
			</ul>
		</nav>
	</div>
</header>

app/views/welcome/home.html.erb
<div class="row">
  <%=render 'users/aside',user:@user,micropost:@micropost %>
  <div class="col-md-6">
    <h3>Microposts Feed</h3>
    <%= render @microposts %>
    <%= will_paginate @microposts,previous_label:"Previous",next_label:"Next",inner_window:1,outer_window:1%>
  </div>
  <%= render 'comments/zhuanfa'%>
</div>

app/views/welcome/index.html.erb
<h1>Hello, blog!</h1>

<img src="https://gss0.baidu.com/7Po3dSag_xI4khGko9WTAnF6hhy/zhidao/pic/item/d1160924ab18972b53f06221e4cd7b899f510a16.jpg" width="600" height="380" class="center-block"/>